### ISSUE TITLE
Does this project support existing WordPress themes/modules/plugins?

### ISSUE THREAD

**Issue by brody2consult** [ramsaylanier/WordpressExpress#11]
I just discovered this project, so cool! Does it support the themes/modules/plugins that have made WordPress so great over the years?

If not, what would it take to add such support?

**Comment by ramsaylanier** [comment]
This project does not currently work with any existing themes. Most plugins will also not work, as they usually affect the front-end. Plugins that only effect back-end setup, such as Advanced Custom Fields, will work. Most plugins that use shortcodes are included in either a PHP template, or the post_content field and are rendered on the server via PHP. Since this project doesn't use any PHP, shortcodes won't work.

I don't think working with themes will ever be on the roadmap. I know working with built-in WP shortcodes is on the road map - things like [caption], etc. should work, but don't currently.

This project is really aimed for Javascript developers to make their own plugins, probably via NPM.
