### ISSUE TITLE
Page templates

### ISSUE THREAD

**Issue by Maximilianos** [ramsaylanier/WordpressExpress#14]
I think I read somewhere you were looking for the best way to handle Page Templates in WordExPress. I am working on a project similar to this one and the solution I am using is using a plugin in the WordPress Install wherein I register custom page templates programmatically and it is working well for me.

I also made a gist for some more details on the how: https://gist.github.com/Maximilianos/b21020ecceaa67650d01

**Comment by ramsaylanier** [comment]
This is cool! And I might actually use it for a different project - but it's not what I'm looking for in this project. To be clear, I don't want to use any .php templates. I had the idea that using custom fields I could query the page, get its metadata (which would be something like "react_layout_component") and then it would use a React Component to layout the page, since the entire front end is in React. 

The problem I'm running into here is that first GraphQL has to query the page and get its metadata, then re-run the query with the metadata for the layout, which doesn't work.

**Comment by ramsaylanier** [comment]
For now, I've actually moved away from this idea, and I'm using routing and page-names to select templates.

``` javascript
import PostList from '../posts/PostList.js';
import DefaultLayout from './DefaultLayout.js';
import FrontPageLayout from './FrontPageLayout.js';

const Layouts = {
  'Default': {
    Component: DefaultLayout
  },
  'FrontPage': {
    Component: FrontPageLayout
  },
  'articles': {
    Component: PostList,
    postType: 'post',
    limit: 10
  }
};


export default Layouts;
```

This is the main [layouts.js](https://github.com/ramsaylanier/WordPressExpress/blob/master/app/components/layouts/layouts.js) file - you can see that for a page with a slug of 'articles' it will render the PostList component as its Layout. 

This works well - but I really wanted to easily be able to set layouts for pages in the WordPress admin panel.

**Comment by Maximilianos** [comment]
I get what you're saying about re-running the queries. I've yet to hit on that snag in my project but I can see it being a pain point soon.

The trouble with your solution as I've understood it, is that it is hard to scale. Of course it may never have been intended to scale and that is of course fine. My project has multilingual content so multiple slugs per layout and our content/seo teams want to be able to create new pages and change the post slugs whenever they want. If I've understood it correctly I would have to constantly manually maintain this list of layouts.

Perhaps there is a way to generate this list of layouts on the php side, where the page templates are managed by WordPress, and then these get given to the app to consume for all subsequent requests.

**Comment by ramsaylanier** [comment]
Yeah, I know the setup isn't ideal and I'm aware it doesn't scale well. I think a lot of the answers will get solved once server-side rendering works that way the layout field can be determined before it gets sent to the client.

**Comment by ramsaylanier** [comment]
Can you give me an example of some of your slugs @Maximilianos ? I want to test some ideas out that might work to make this more scalable.

**Comment by ramsaylanier** [comment]
update on this: In Relay v0.7.1 apparently you can pass in an array of fragments in Relay.QL - I'm working on a solution that involves running a node script that will read comments in layout component files (just like existing WordPress PHP templates work) and then create custom field groups in the WordPress database. The other part of this solution is then writing a simple WordPress plugin that will offer a custom meta box with the parse layout templates as a select. So basically, it will work just like regular WordPress templates except instead of a PHP file it will be a React component. 

The only thing is that for each page you will have to manually select the layout to use - there will not be any automated template mapping like WordPress has.
