### ISSUE TITLE
WP SQL example?

### ISSUE THREAD

**Issue by mcrider** [ramsaylanier/WordpressExpress#2]
Do you have an SQL dump you can share that works with this app?  I installed WP from scratch and got a big red error (TypeError: Cannot read property 'post_title' of null).  I haven't seen any documentation on how to configure my WP install.  Thanks!

**Comment by ramsaylanier** [comment]
You're right - I need to add documentation about that. I'm working on it.

In the meantime, just create a page in WordPress with the title "Homepage"

**Comment by ramsaylanier** [comment]
The other option is to change the page that gets loaded in the [LandingPage](https://github.com/ramsaylanier/WordpressExpress/blob/master/app/components/pages/LandingPage.js) component. 

```
export default Relay.createContainer(LandingPage, {
  fragments: {
    viewer: () => Relay.QL`
      fragment on User {
        page(post_name:"homepage"){
                    id,
                    post_title
                    post_content
                }
      }
    `,
  },
});
```

Instead of "homepage" you can change it to anything you want if you have existing pages. Keep in mind it takes the post-name (aka slug) not the post-title.

**Comment by ramsaylanier** [comment]
Documentation has been updated. Closing.
